# ===============================
# = DATA SOURCE
# ===============================


spring:
  datasource:
           hikari:   # Set here configurations for the database connection
                    connection-test-query: SELECT 1 FROM SYSIBM.SYSDUMMY1
           url: jdbc:as400://10.212.33.151/AUTO
           username: weblogin
           password: jlo98765
           driver-class-name: com.ibm.as400.access.AS400JDBCDriver
  jpa:
        database-platform: org.hibernate.dialect.DB2400Dialect
        database: DB2
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false

# ======================================
# = Enable SQL Parameter Tracing in Logs
# ======================================
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#        SQL: debug
