# ===============================
# = DATA SOURCE
# ===============================


spring:
  datasource:
           hikari:   # Set here configurations for the database connection
                    connection-test-query:
           url: 
           username: 
           password: 
           driver-class-name: 
  jpa:
        database-platform: 
        database: 
        show-sql: 
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false

# ======================================
# = Enable SQL Parameter Tracing in Logs
# ======================================
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#        SQL: debug
amsi:
  url: http://www.clk-pm.net/AMSIweb/edexweb/esite/leasing.asmx
  username: fasrclk
  password: fasrclk
  portfolio: esite clk
